Added Build command
dil-classroom/projet-dil-diep_jean_rodr_stocc pull request #19
Opened 2022-03-11 08:23 UTC by Isotech42

2022-03-11 22:22 UTC, clemdiep-heig requested changes
As we have to do _subcommands_, the class `Build` as to be added in the main class.

That class, `Starter`, will be added by the pull request #18. So either:
 - you wait for it to be merged on main then merge main on this branch and then add it (you can review this PR, it will be faster 👀)
 - you merge the branch from the PR and then make the change

Multiple _subcommands_ are added like so `subcommands = {New.class, Build.class}` in the `@Command` annotation.

2022-03-12 16:36 UTC, Isotech42 commented
I actually done, in fact, the modification on the Starter flie too, but I was waiting #18 to be merged. But @dylanrodr-heig is slow :p

2022-03-12 17:11 UTC, dylanrodr-heig approved these changes

2022-03-12 17:12 UTC, clemdiep-heig approved these changes

2022-03-12 17:12 UTC, merged