Code refactoring
dil-classroom/projet-dil-diep_jean_rodr_stocc pull request #56
Opened 2022-04-17 20:23 UTC by clemdiep-heig

close #55

2022-04-20 13:18 UTC, dylanrodr-heig requested changes
It's quite perfect! Just need some changes.
You can also update the package `org.commonmark` at line 70 in the file `pom.xml` to `0.18.2`.

2022-04-20 13:18 UTC, dylanrodr-heig commented on src/main/java/ch/heigvd/statique/convertors/Builder.java
> +   * @param buildDirectory build directory
```suggestion
   * @param buildDestination build directory
```

2022-04-20 13:18 UTC, dylanrodr-heig commented on src/main/java/ch/heigvd/statique/utils/Config.java
> +   * @param config The config to merge with.
```suggestion
   * @param other The config to merge with.
```

2022-04-20 13:18 UTC, dylanrodr-heig commented on src/main/java/ch/heigvd/statique/utils/Page.java
> +   * @param html The HTML to write.
```suggestion
   * @param content The HTML to write.
```

2022-04-20 13:18 UTC, dylanrodr-heig commented on src/main/java/ch/heigvd/statique/utils/Page.java
> +   * @param markdown The markdown to convert.
```suggestion
   * @param md The markdown to convert.
```

2022-04-20 17:18 UTC, dylanrodr-heig approved these changes

2022-04-24 18:32 UTC, Isotech42 approved these changes
Wow, quite a cleanup in there. It really needed to be done at some point. Thanks for the work!

2022-04-24 18:32 UTC, merged