Serve command created
dil-classroom/projet-dil-diep_jean_rodr_stocc pull request #60
Opened 2022-04-29 19:29 UTC by dylanrodr-heig

Command that creates an HTTP server using `build` site folder.

2022-04-29 21:08 UTC, clemdiep-heig requested changes
It's good ! I have some request.

1. I think that adding a test for the 404 page would be greate too
2. Also, reconsider the 403 page has we discussed in private
3. And one comment in the code

2022-04-30 09:34 UTC, clemdiep-heig requested changes
Well, the 403 error wasn't complete for what we wanted.

Also, added a comment that a forgot in my first review.

Normally, you can commit all changes without problem

🍺

2022-04-30 09:34 UTC, clemdiep-heig commented on src/main/java/ch/heigvd/statique/utils/Server.java
> +            if(uri.toString().contains("/../")){
This will allow access with `/..%2findex.md` (`%2f` correspond to `/`)

Use this to handle instead

```suggestion
            if(!file.getPath().startsWith(site.toString())) {
```

2022-04-30 09:34 UTC, clemdiep-heig commented on src/main/java/ch/heigvd/statique/utils/Server.java
> +        this.site = site;
This is for handle the 403 error correctly, comment on the line 63

```suggestion
        this.site = site.toAbsolutePath().normalize();
```

2022-04-30 09:34 UTC, clemdiep-heig commented on src/main/java/ch/heigvd/statique/utils/Server.java
> +            File file = new File(site + uri.getPath()).getCanonicalFile();
When accessing a directory, it would be good to get the index.html file in this directory as destination file

```suggestion
            File file = new File(site + uri.getPath()).getCanonicalFile();
            
            // Get index.html if the destination is a directory
            if (file.isDirectory()) {
                file = new File(file, "index.html");
            }
```

2022-04-30 10:49 UTC, clemdiep-heig approved these changes

2022-04-30 15:06 UTC, Isotech42 approved these changes
It's a very good job ! Even I wouldn't make it so great

2022-04-30 15:06 UTC, merged