Automatic release and version update
dil-classroom/projet-dil-diep_jean_rodr_stocc pull request #61
Opened 2022-04-30 17:39 UTC by clemdiep-heig

I have tested it in another project, all seems to be fine.

It will update the version in `pom.xml` and `version.txt` if needed.\
The release message should contains all pull request title has changelog.

closes #49

2022-05-01 10:24 UTC, dylanrodr-heig requested changes
I tried to publish a release after forking the repository. But it didn't seemed to work.
Maybe I'm using it wrong :0

[fork link](https://github.com/dylanrodr-heig/dil-test/releases/tag/v1.0.2)

2022-05-01 10:31 UTC, dylanrodr-heig approved these changes
Good job ! 🥇

2022-05-04 10:27 UTC, Isotech42 requested changes

2022-05-04 10:27 UTC, Isotech42 commented on .github-cli/update-version
> +git config --global user.name $NAME
Hum.. I don't understand where and why you have to use these $EMAIL and $NAME ?
I think we can delete these lines
```suggestion

```

2022-05-04 10:28 UTC, clemdiep-heig commented on .github-cli/update-version
> +git config --global user.name $NAME
Ho yes, it was some old lines from previous attempts !

2022-05-04 10:30 UTC, Isotech42 approved these changes
For me it's all perfect ! Thank you ! 🍻  (except that there is spaces...)

2022-05-04 10:30 UTC, merged