Ft 51 template engine
dil-classroom/projet-dil-diep_jean_rodr_stocc pull request #63
Opened 2022-05-05 10:42 UTC by MordoJ

Now templates work properly. This only catch is that links in pages work only on the server, not locally on a device. The only thing left for this task though is to add tests.

2022-05-07 12:52 UTC, clemdiep-heig requested changes
Well, there some big issue with what you commited

1. Remove the directory `site/build`, we don't want it on the git.
2. Keep the test that does not need big rework
3. Correct the `build` command so that it won't copy the `template` folder
4. Correct the `init` command so that it will add a `template` by default

2022-05-07 12:52 UTC, clemdiep-heig commented on pom.xml
> +
I don't think it's necessary to have twice the dependency ?

2022-05-07 12:52 UTC, clemdiep-heig commented on src/main/java/ch/heigvd/statique/utils/Config.java
> +  public Map<String, Object> config;
Keep it `private`

2022-05-07 12:52 UTC, clemdiep-heig commented on src/main/java/ch/heigvd/statique/utils/Config.java
> +    return new Config(temp);
We have done that to test how `Handlebars.java` works, but it think some rework would be needed for this class, like adding a parameter for the prefixes some where. I will create an issue for that.

2022-05-07 12:52 UTC, clemdiep-heig commented on src/main/java/ch/heigvd/statique/utils/Page.java
> +  public Page(Path fromPath, Path toPath, Template temp) {
Add the comment for the new parameter

2022-05-11 13:35 UTC, MordoJ commented on pom.xml
> +
You're right, I don't know how I ended up have it twice.

2022-05-11 13:37 UTC, MordoJ commented on src/main/java/ch/heigvd/statique/utils/Config.java
> +  public Map<String, Object> config;
I've changed it back top ✨private✨

2022-05-11 13:45 UTC, MordoJ commented on src/main/java/ch/heigvd/statique/utils/Page.java
> +  public Page(Path fromPath, Path toPath, Template temp) {
Now there's a new shiny comment just to describe this parameter 💫

2022-05-11 14:07 UTC, MordoJ commented
All requested changes has been applied.

2022-05-15 09:54 UTC, dylanrodr-heig approved these changes

2022-05-15 09:54 UTC, merged