Added watch option to build and serve command
dil-classroom/projet-dil-diep_jean_rodr_stocc pull request #69
Opened 2022-05-17 10:43 UTC by dylanrodr-heig

2022-05-17 20:05 UTC, clemdiep-heig approved these changes
Seems great ! 🍻

2022-05-17 20:14 UTC, clemdiep-heig approved these changes
Oupsi, forgot to test to modify the templates.

It's doesn't rebuild the site pages. The problem seems to be related to watching in a sub-folder, I tested with a file `pages/page1.md` too and when it's modified no rebuild is done.

2022-05-17 20:16 UTC, clemdiep-heig requested changes
Wrong approvement with previous comment...

Thanks GitHub to not let me delete my message :)

2022-05-18 16:38 UTC, dylanrodr-heig commented
@clemdiep-heig corrected :D

2022-05-22 17:23 UTC, clemdiep-heig approved these changes
Great sub folder are working now !

Just a little comment

2022-05-22 17:23 UTC, clemdiep-heig commented on src/main/java/ch/heigvd/statique/utils/Watcher.java
> +                if (ENTRY_CREATE.equals(kind)) {
Couldn't you merge those two if together ?

```suggestion
                if (ENTRY_CREATE.equals(kind)) {
                    //this is not a complete path
                    Path path = ev.context();
                    //need to get parent path
                    Path parentPath = keyPathMap.get(key);
                    //get complete path
                    path = parentPath.resolve(path);

                    try {
                        registerDir(path);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
```

2022-05-23 06:43 UTC, dylanrodr-heig commented on src/main/java/ch/heigvd/statique/utils/Watcher.java
> +                if (ENTRY_CREATE.equals(kind)) {
Yes, you're right ! Thx ^^

2022-05-23 06:46 UTC, dylanrodr-heig commented
@clemdiep-heig Requested changes done ^^

2022-05-23 07:51 UTC, clemdiep-heig approved these changes

2022-05-23 08:09 UTC, Isotech42 approved these changes
Wonderful work !

2022-05-23 08:09 UTC, merged