Adding support of Jacoco in Maven dependencies
dil-classroom/projet-dil-diep_jean_rodr_stocc pull request #73
Opened 2022-05-23 20:46 UTC by Isotech42

I added the dependency of Jacoco in the `pom.xml`.
If you launch the command `mvn jacoco:report`, a folder `target/site/jacoco` will be created containing a whole bunch of stuff indicating the code coverage of our tests.
There is an `index.html` file to see easily all the statistics.

2022-05-23 21:11 UTC, clemdiep-heig approved these changes
Nice work!

We will have to add it to an automatic report with some other code inspection

2022-05-24 09:41 UTC, clemdiep-heig requested changes
Oupsi, I missed something

2022-05-24 09:41 UTC, clemdiep-heig commented on pom.xml
> +            </configuration>
I didn't see that but it create a directory with the name `${project.target.directory}` when executing `mvn clean install`. I tested and we can just remove those lines and it works fine.

```suggestion
```

2022-05-24 09:48 UTC, Isotech42 commented on pom.xml
> +            </configuration>
Seriously ?? Ooooops, didn't see that

2022-05-24 09:49 UTC, clemdiep-heig approved these changes

2022-05-24 09:49 UTC, dylanrodr-heig approved these changes

2022-05-24 09:50 UTC, merged