Added some tests
dil-classroom/projet-dil-diep_jean_rodr_stocc pull request #77
Opened 2022-05-24 08:54 UTC by MordoJ

Some tests are already working and can be added to the main project. However not all of them are done so the branch shouldn't be deleted.

2022-05-24 09:27 UTC, clemdiep-heig requested changes
I added some comments on the code.

And also remove the folder `site/build` 😄

2022-05-24 09:27 UTC, clemdiep-heig commented on src/test/java/ch/heigvd/statique/utils/PageTest.java
> +    Path testFolderPath = Path.of("site/build/tests");
Create a folder in the temporary folder. You can see in `YamlConvertorTest.java` the function `createFiles()` for an example.

2022-05-24 09:27 UTC, clemdiep-heig commented on src/test/java/ch/heigvd/statique/utils/PageTest.java
> +      writeFile(String.valueOf(filesPathReal.get(i)), filesContent.get(i));
You could try to use the ressources folder in the test. It's better to really seperate all things that are used to test like so they are totaly independent.

See in `UtilsTest.java` the test `copyFileFromRessources()` for an exemple

2022-05-24 09:27 UTC, clemdiep-heig commented on src/test/java/ch/heigvd/statique/utils/PageTest.java
> +          "</html>";
After the discussion we had with the assistant for the first sprint, I think it would be better to check not all the file but revelant part of it. For example, where there is the variables that come from `config.yaml` and from the yaml part of the mardown file.

Some example:

- `<title>Mon site internet | Home page</title>`
- `<h1>Mon site internet</h1>`

Also I think, it would be good to make custom files for the tests with multiple different cases

2022-06-01 12:18 UTC, MordoJ commented on src/test/java/ch/heigvd/statique/utils/PageTest.java
> +    Path testFolderPath = Path.of("site/build/tests");
Tests files are now created in the temp folder.

2022-06-01 13:13 UTC, clemdiep-heig requested changes
Good all is fine, except some function name that are not respecting the convention we set.

2022-06-01 13:13 UTC, clemdiep-heig commented on src/test/java/ch/heigvd/statique/utils/BuildTemplateTest.java
> +  public void CreateTestFiles() throws IOException {
Naming convention

```suggestion
  public void createTestFiles() throws IOException {
```

2022-06-01 13:13 UTC, clemdiep-heig commented on src/test/java/ch/heigvd/statique/utils/BuildTemplateTest.java
> +  public void EraseTestFiles() throws IOException {
Naming convention

```suggestion
  public void eraseTestFiles() throws IOException {
```

2022-06-01 13:13 UTC, clemdiep-heig commented on src/test/java/ch/heigvd/statique/commands/BuildTest.java
> +  void EraseFolder() throws IOException {
Naming convention

```suggestion
  void eraseFolder() throws IOException {
```

2022-06-01 13:27 UTC, MordoJ reviewed
Added Clément's changes.

2022-06-01 13:28 UTC, clemdiep-heig submitted a review, later dismissed
YaY 🍻

2022-06-05 09:21 UTC, Isotech42 reviewed
Have you thought about reformatting the code with IntelliJ's tool? I see a lot of unnecessary import.
In IntelliJ : Right click on the file -> Reformat Code -> Check the boxes -> Ok

2022-06-07 14:44 UTC, MordoJ commented
> Have you thought about reformatting the code with IntelliJ's tool? I see a lot of unnecessary import. In IntelliJ : Right click on the file -> Reformat Code -> Check the boxes -> Ok

It's done!

2022-06-07 14:55 UTC, clemdiep-heig approved these changes
🍻

2022-06-07 16:07 UTC, merged