Update the user manual with the command publish
dil-classroom/projet-dil-diep_jean_rodr_stocc pull request #88
Opened 2022-06-15 23:32 UTC by Isotech42

I added a few lines about how to use the `publish` command.

2022-06-15 23:35 UTC, clemdiep-heig requested changes

2022-06-15 23:35 UTC, clemdiep-heig commented on README.md
> +    `publish <PATH> <remote_path> <ssh_url>` : Publie le site web statique sur un dépôt GIT en SSH.
It's not a git repo but it only copy the file to the remote path

2022-06-15 23:35 UTC, clemdiep-heig commented on README.md
> +Par défaut, l'application récupère les clés SSH dans `~/.ssh/id_rsa`, cependant, il est possible d'ajouté l'option `-p` ou `--password` afin d'utiliser un mot de passe (celui-ci étant demandé **après
```suggestion
Par défaut, l'application récupère les clés SSH dans `~/.ssh/id_rsa`, cependant, il est possible d'ajouter l'option `-p` ou `--password` afin d'utiliser un mot de passe (celui-ci étant demandé **après** avoir lancé la commande).
```

2022-06-15 23:40 UTC, Isotech42 commented on README.md
> +    `publish <PATH> <remote_path> <ssh_url>` : Publie le site web statique sur un dépôt GIT en SSH.
I update the sentence, let me know if it's better.

2022-06-15 23:44 UTC, clemdiep-heig approved these changes
Perfect 🍺

2022-06-16 00:58 UTC, MordoJ approved these changes
Perfect 👌

2022-06-16 00:59 UTC, merged